import { lib, game, ui, get, ai, _status } from "noname";
const characters = {
	//武将信息
	//手杀
	old_jm_yuanshu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["mbjimi", "old_mbmaodie"],
		img: "image/character/jm_yuanshu.jpg",
		dieAudios: ["jm_yuanshu"],
		names: "袁|术",
	},
	old_mb_caomao: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["old_mbqianlong", "old_mbweitong"],
		isZhugong: true,
	},
	old_new_simayi: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["old_jilin", "old_yingyou", "old_yingtian"],
		img: "image/character/new_simayi.jpg",
		dieAudios: ["new_simayi"],
		groupInGuozhan: "wei",
		names: "司马|懿",
	},
	old_mb_shen_jiangwei: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["old_guxuan", "old_juejin", "old_huitian", "old_xingzhen"],
		img: "image/character/mb_shen_jiangwei.jpg",
		groupInGuozhan: "shu",
	},
	oldx_mb_shen_jiangwei: {
		sex: "male",
		group: "shen",
		hp: 1,
		maxHp: 4,
		skills: ["old_guxuan", "oldx_juejin", "old_huitian", "oldx_xingzhen"],
		img: "image/character/mb_shen_jiangwei.jpg",
		groupInGuozhan: "shu",
	},
	old_mb_jushou: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["old_xinjianying", "xinshibei"],
		img: "image/character/xin_jushou.jpg",
		dieAudios: ["xin_jushou"],
	},
	old_mb_zhuzhi: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["old_sbanguo"],
		img: "image/character/xin_zhuzhi.jpg",
		dieAudios: ["xin_zhuzhi"],
	},
	old_mb_sp_zhenji: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["old_mbbojian", "twmbjiwei"],
		img: "image/character/mb_sp_zhenji.jpg",
		dieAudios: ["mb_sp_zhenji"],
	},
	old_fuqian: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["old_jueyong", "old_poxiang"],
		img: "image/character/fuqian.jpg",
		dieAudios: ["fuqian"],
	},
	old_mb_guozhao: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["old_yichong", "old_wufei"],
		img: "image/character/xin_guozhao.jpg",
		dieAudios: ["xin_guozhao"],
	},
	old_mb_chengui: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["old_guimou", "zhouxian"],
		img: "image/character/mb_chengui.jpg",
		dieAudios: ["mb_chengui"],
	},
	old_yangfu: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["oldx_jiebing", "old_hannan"],
		img: "image/character/yangfu.jpg",
		dieAudios: ["yangfu"],
	},
	old_wangling: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["mouli", "zifu"],
		img: "image/character/wangling.jpg",
		dieAudios: ["wangling"],
		clans: ["太原王氏"],
	},
	old_sp_wangshuang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["yiyong", "old_shanxie"],
		img: "image/character/sp_wangshuang.jpg",
		dieAudios: ["sp_wangshuang"],
	},
	old_wujing: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["heji", "old_liubing"],
		img: "image/character/wujing.jpg",
		dieAudios: ["wujing"],
	},
	old_sp_xinpi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["old_spyinju", "spchijie"],
		img: "image/character/sp_xinpi.jpg",
		dieAudios: ["sp_xinpi"],
	},
	old_qiaogong: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["old_yizhu", "luanchou"],
		img: "image/character/qiaogong.jpg",
		dieAudios: ["qiaogong"],
		names: "桥|null",
	},
	old_sp_lvfan: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["spdiaodu", "spdiancai", "spyanji"],
		img: "image/character/sp_lvfan.jpg",
		dieAudios: ["sp_lvfan"],
	},
	old_xin_zhangzhongjing: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["jishi", "liaoyi", "binglun"],
		img: "image/character/zhangzhongjing.jpg",
		dieAudios: ["zhangzhongjing"],
	},
	old_sp_zhujun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["yangjie", "zjjuxiang", "houfeng"],
		img: "image/character/sp_zhujun.jpg",
		dieAudios: ["sp_zhujun"],
	},
	old_yj_zhoubuyi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["old_mbhuiyao", "old_mbquesong"],
		img: "image/character/yj_zhoubuyi.jpg",
		dieAudios: ["yj_zhoubuyi"],
	},
	old_shenpei: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["shouye", "liezhi"],
		img: "image/character/shenpei.jpg",
		dieAudios: ["shenpei"],
	},
	old_mb_sp_guanqiujian: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["old_mbcuizhen", "mbkuili"],
		img: "image/character/mb_sp_guanqiujian.jpg",
		dieAudios: ["mb_sp_guanqiujian"],
		names: "毌丘|俭",
	},
	old_mb_wangjing: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["mbzujin", "old_mbjiejian"],
		img: "image/character/mb_wangjing.jpg",
		dieAudios: ["mb_wangjing"],
	},
	oldx_sp_jianggan: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["old_spdaoshu", "spdaizui"],
		img: "image/character/sp_jianggan.jpg",
		dieAudios: ["sp_jianggan"],
	},
	old_liwei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["old_jiaohua"],
		img: "image/character/liwei.jpg",
		dieAudios: ["tw_liwei"],
	},
	old_friend_xushu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["old_friendxiaxing", "friendqihui", "friendxushugongli"],
		img: "image/character/friend_xushu.jpg",
		dieAudios: ["friend_xushu"],
	},
	old_pot_lougui: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["potguansha", "old_potjiyu"],
		img: "image/character/pot_lougui.jpg",
		dieAudios: ["pot_lougui"],
	},
	old_sb_huangzhong: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["old_sbliegong"],
		img: "image/character/sb_huangzhong.jpg",
		dieAudios: ["sb_huangzhong"],
	},
	old_sb_gongsunzan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["sbyicong", "old_sbqiaomeng"],
		img: "image/character/sb_gongsunzan.jpg",
		dieAudios: ["sb_gongsunzan"],
		names: "公孙|瓒",
	},
	old_sb_sunquan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["old_sbzhiheng", "old_sbtongye", "sbjiuyuan"],
		img: "image/character/sb_sunquan.jpg",
		dieAudios: ["sb_sunquan"],
		isZhugong: true,
	},
	old_sb_huanggai: {
		sex: "male",
		group: "wu",
		hp: 2,
		maxHp: 4,
		hujia: 2,
		skills: ["sbkurou", "old_sbzhaxiang"],
		img: "image/character/sb_huanggai.jpg",
		dieAudios: ["sb_huanggai"],
	},
	old_sb_ganning: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["old_sbqixi", "old_sbfenwei"],
		img: "image/character/sb_ganning.jpg",
		dieAudios: ["sb_ganning"],
	},
	old_sb_xiaoqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["old_sbtianxiang", "xinhongyan"],
		img: "image/character/sb_xiaoqiao.jpg",
		dieAudios: ["sb_xiaoqiao"],
		names: "桥|null",
	},
	old_sb_daqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["old_sbguose", "sbliuli"],
		img: "image/character/sb_daqiao.jpg",
		dieAudios: ["sb_daqiao"],
		names: "桥|null",
	},
	old_sb_sunce: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["old_sbjiang", "old_sbhunzi", "old_sbzhiba"],
		img: "image/character/sb_sunce.jpg",
		dieAudios: ["sb_sunce"],
		isZhugong: true,
	},
	old_sb_sp_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["old_sbhuoji", "old_sbkanpo"],
		img: "image/character/sb_sp_zhugeliang.jpg",
		dieAudios: ["sb_sp_zhugeliang"],
		names: "诸葛|亮",
	},
	old_sb_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["old_sbguanxing", "old_sbkongcheng"],
		img: "image/character/sb_zhugeliang.jpg",
		dieAudios: ["sb_zhugeliang"],
		names: "诸葛|亮",
	},
	oldx_sb_sp_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["oldx_sbhuoji", "oldx_sbkanpo"],
		img: "image/character/sb_sp_zhugeliang.jpg",
		dieAudios: ["sb_sp_zhugeliang"],
		names: "诸葛|亮",
	},
	oldx_sb_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["oldx_sbguanxing", "oldx_sbkongcheng"],
		img: "image/character/sb_zhugeliang.jpg",
		dieAudios: ["sb_zhugeliang"],
		names: "诸葛|亮",
	},
	old_sb_menghuo: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["sbhuoshou", "old_sbzaiqi"],
		img: "image/character/sb_menghuo.jpg",
		dieAudios: ["sb_menghuo"],
		doubleGroup: ["shu", "qun"],
	},
	old_sb_zhurong: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["old_sblieren", "old_sbjuxiang"],
		img: "image/character/sb_zhurong.jpg",
		dieAudios: ["sb_zhurong"],
		doubleGroup: ["shu", "qun"],
	},
	old_sb_guanyu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["old_sbwusheng", "sbyijue"],
		img: "image/character/sb_guanyu.jpg",
		dieAudios: ["sb_guanyu"],
	},
	old_sb_zhaoyun: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["old_sblongdan", "old_sbjizhu"],
		img: "image/character/sb_zhaoyun.jpg",
		dieAudios: ["sb_zhaoyun"],
	},
	old_sb_fazheng: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["old_sbxuanhuo", "old_sbenyuan"],
		img: "image/character/sb_fazheng.jpg",
		dieAudios: ["sb_fazheng"],
	},
	old_sb_xuhuang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["old_sbduanliang", "sbshipo"],
		img: "image/character/sb_xuhuang.jpg",
		dieAudios: ["sb_xuhuang"],
	},
	old_sb_yuanshao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["old_sbluanji", "old_sbxueyi"],
		img: "image/character/sb_yuanshao.jpg",
		dieAudios: ["sb_yuanshao"],
		isZhugong: true,
	},
	old_sb_huaxiong: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 5,
		skills: ["new_reyaowu", "sbyangwei"],
		img: "image/character/sb_huaxiong.jpg",
		dieAudios: ["sb_huaxiong"],
	},
	old_sb_handang: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["sbgongqi", "old_sbjiefan"],
		img: "image/character/sb_handang.jpg",
		dieAudios: ["sb_handang"],
	},
	old_sb_caopi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["twxingshang", "twfangzhu", "twsongwei"],
		img: "image/character/sb_caopi.jpg",
		dieAudios: ["sb_caopi"],
		isZhugong: true,
	},
	old_sb_jiaxu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["old_sbwansha", "old_sbluanwu", "sbweimu"],
		img: "image/character/sb_jiaxu.jpg",
		dieAudios: ["sb_jiaxu"],
	},
	old_sb_zhugejin: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["old_sbhuanshi", "old_sbhongyuan", "old_sbmingzhe"],
		img: "image/character/sb_zhugejin.jpg",
		dieAudios: ["sb_zhugejin"],
		names: "诸葛|瑾",
	},
	old_sb_zhangliao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["old_sbtuxi", "old_sbdengfeng"],
		img: "image/character/sb_zhangliao.jpg",
		dieAudios: ["sb_zhangliao"],
	},
	old_sb_zhanghe: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["old_sbqiaobian"],
		img: "image/character/sb_zhanghe.jpg",
		dieAudios: ["sb_zhanghe"],
	},
	old_sb_guojia: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["sbtiandu", "old_sbyiji"],
		img: "image/character/sb_guojia.jpg",
		dieAudios: ["sb_guojia"],
	},
	old_sb_gaoshun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["old_sbxianzhen", "sbjinjiu"],
		img: "image/character/sb_gaoshun.jpg",
		dieAudios: ["sb_gaoshun"],
	},
	old_sb_xiahouyuan: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["sbshensu", "old_sbzhengzi"],
		img: "image/character/sb_xiahouyuan.jpg",
		dieAudios: ["sb_xiahouyuan"],
		names: "夏侯|渊",
	},
	old_sb_lvbu: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["old_sbwushuang", "old_sbliyu"],
		img: "image/character/sb_lvbu.jpg",
		dieAudios: ["sb_lvbu"],
	},
	old_pot_taishici: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["old_pothanzhan", "old_potzhanlie", "old_potzhenfeng"],
		img: "image/character/pot_taishici.jpg",
		dieAudios: ["pot_taishici"],
		names: "太史|慈",
	},
	old_pot_chendao: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["potwanglie", "old_pothongyi"],
		img: "image/character/pot_chendao.jpg",
		dieAudios: ["pot_chendao"],
	},
	old_pot_yuji: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["old_potdaozhuan", "old_potfuji"],
		img: "image/character/pot_yuji.jpg",
		dieAudios: ["pot_yuji"],
	},
	old_zhangbu: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["old_mbchengxiong", "old_mbwangzhuang"],
		img: "image/character/zhangbu.jpg",
		dieAudios: ["zhangbu"],
	},
	old_wuke: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["old_mbanda", "old_mbzhuguo"],
		img: "image/character/wuke.jpg",
		dieAudios: ["wuke"],
		names: "吴|null",
	},
	old_pot_weiyan: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["old_potzhongao", "old_potzhuangshi", "potyinzhan"],
		img: "image/character/pot_weiyan.jpg",
		dieAudios: ["pot_weiyan"],
	},
	old_mb_chenzhi: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["mbquanchong", "old_mbrenxing"],
		img: "image/character/mb_chenzhi.jpg",
		dieAudios: ["mb_chenzhi"],
	},
	old_guoyuan: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["mbqingdao", "old_mbxiugeng", "old_mbchenshe"],
		img: "image/character/guoyuan.jpg",
		dieAudios: ["guoyuan"],
	},
	old_mb_caocao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["old_mblingfa", "twzhian"],
		img: "image/character/mb_caocao.jpg",
		dieAudios: ["mb_caocao"],
		tempname: ["mb_caocao"],
	},
	old_pot_lusu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["old_pothaoshi", "potdimeng"],
		img: "image/character/pot_lusu.jpg",
		dieAudios: ["pot_lusu"],
	},
	old_mb_mengda: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["old_mbjili", "mbshishu"],
		img: "image/character/mb_mengda.jpg",
		dieAudios: ["mb_mengda"],
	},
	old_pot_xinxianying: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["old_potjiejie", "potqingshi"],
		img: "image/character/pot_xinxianying.jpg",
		dieAudios: ["pot_xinxianying"],
	},
	old_sb_jiangwei: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 1,
		skills: ["sbtiaoxin", "old_sbzhiji"],
		img: "image/character/sb_jiangwei.jpg",
		dieAudios: ["sb_jiangwei"],
	},
	old_mb_zhangyan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["old_mbfeijing", "old_mbxiaoge"],
		img: "image/character/mb_zhangyan.jpg",
		dieAudios: ["mb_zhangyan"],
	},
	old_mb_cuilingyi: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["old_mbcaiqiu", "old_mbxishang"],
		img: "image/character/mb_cuilingyi.jpg",
		dieAudios: ["mb_cuilingyi"],
		names: "崔|null",
	},
	old_pangxi: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["old_mbxuye", "old_mbkuangxiang"],
		img: "image/character/pangxi.jpg",
		dieAudios: ["pangxi"],
	},
	old_pot_dengai: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["old_pottuntian", "old_potjixi", "old_potzaoxian"],
		img: "image/character/pot_dengai.jpg",
		dieAudios: ["pot_dengai"],
	},
	old_mb_liuhui: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["old_mbgeyuan", "old_mbchongcha"],
		img: "image/character/mb_liuhui.jpg",
		dieAudios: ["mb_liuhui"],
	},
	old_mb_sunquan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["old_mb_chulie", "old_mb_shehu"],
		img: "image/character/mb_sunquan.jpg",
		dieAudios: ["mb_sunquan"],
	},
	old_hefei_zhangliao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["old_hefeichonglei", "old_hefeidangshi", "old_hefeiheyuzhangliao"],
		img: "image/character/hefei_zhangliao.jpg",
		dieAudios: ["hefei_zhangliao"],
		tempname: ["hefei_zhangliao"],
	},
	//OL
	old_shen_caopi: {
		sex: "male",
		group: "shen",
		hp: 6,
		skills: ["old_chuyuan", "old_dengji"],
		img: "image/character/shen_caopi.jpg",
		dieAudios: ["shen_caopi"],
		groupInGuozhan: "wei",
		tempname: ["shen_caopi"],
	},
	oldx_clan_xuncai: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["oldx_clanlieshi", "clandianzhan", "clanhuanyin", "clandaojie"],
		img: "image/character/clan_xuncai.jpg",
		dieAudios: ["clan_xuncai"],
		clans: ["颍川荀氏"],
		tempname: ["clan_xuncai"],
	},
	old_clan_zhonghui: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 4,
		skills: ["old_clanyuzhi", "old_clanxieshu", "clanbaozu"],
		img: "image/character/clan_zhonghui.jpg",
		dieAudios: ["clan_zhonghui"],
		clans: ["颍川钟氏"],
		tempname: ["clan_zhonghui"],
	},
	old_clan_hanrong: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["old_lianhe", "old_huanjia", "old_xumin"],
		img: "image/character/clan_hanrong.jpg",
		dieAudios: ["clan_hanrong"],
		clans: ["颍川韩氏"],
		tempname: ["clan_hanrong"],
	},
	old_clan_hanshao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["old_fangzhen", "old_liuju", "old_xumin"],
		img: "image/character/clan_hanshao.jpg",
		dieAudios: ["clan_hanshao"],
		clans: ["颍川韩氏"],
		tempname: ["clan_hanshao"],
	},
	old_clan_xunshuang: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["old_clanyangji", "old_clandandao", "old_clanqingli", "clandaojie"],
		img: "image/character/clan_xunshuang.jpg",
		dieAudios: ["clan_xunshuang"],
		clans: ["颍川荀氏"],
		tempname: ["clan_xunshuang"],
	},
	old_clan_yangxiu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["old_clanjiewu", "old_clangaoshi", "clanquhuo"],
		img: "image/character/clan_yangxiu.jpg",
		dieAudios: ["clan_yangxiu"],
		clans: ["弘农杨氏"],
		tempname: ["clan_yangxiu"],
	},
	old_clan_wangmingshan: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["old_clantanque", "old_clanshengmo", "clanzhongliu"],
		img: "image/character/clan_wangmingshan.jpg",
		dieAudios: ["clan_wangmingshan"],
		clans: ["太原王氏"],
		tempname: ["clan_wangmingshan"],
	},
	old_clan_xunyu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["old_clandingan", "old_clanfuning", "clandaojie"],
		img: "image/character/clan_xunyu.jpg",
		dieAudios: ["clan_xunyu"],
		clans: ["颍川荀氏"],
		tempname: ["clan_xunyu"],
	},
	old_clan_xunshi: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["clanqingjue", "old_clanxsyingxiang", "clandaojie"],
		img: "image/character/clan_xunshi.jpg",
		dieAudios: ["clan_xunshi"],
		clans: ["颍川荀氏"],
		tempname: ["clan_xunshi"],
	},
	old_zhanghua: {
		sex: "male",
		group: "jin",
		hp: 3,
		skills: ["olbihun", "olchuanwu", "oljianhe"],
		img: "image/character/zhanghua.jpg",
		dieAudios: ["zhanghua"],
	},
	old_yuanji: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["dcmengchi", "dcjiexing"],
		img: "image/character/yuanji.jpg",
		dieAudios: ["yuanji"],
		names: "袁|null",
	},
	old_tengfanglan: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["old_luochong", "old_aichen"],
		img: "image/character/tengfanglan.jpg",
		dieAudios: ["tengfanglan"],
	},
	old_dengzhong: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["old_dzkanpo", "old_dzgengzhan"],
		img: "image/character/dengzhong.jpg",
		dieAudios: ["dengzhong"],
	},
	old_wangyan: {
		sex: "male",
		group: "jin",
		hp: 3,
		skills: ["yangkuang", "old_cihuang", "old_sanku"],
		img: "image/character/wangyan.jpg",
		dieAudios: ["wangyan"],
	},
	old_ol_luyusheng: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["old_olcangxin", "olrunwei"],
		img: "image/character/ol_luyusheng.jpg",
		dieAudios: ["ol_luyusheng"],
	},
	old_ol_hujinding: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["olqingyuan", "old_olchongshen"],
		img: "image/character/ol_hujinding.jpg",
		dieAudios: ["ol_hujinding"],
	},
	old_ol_feiyi: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["yanru", "old_hezhong"],
		img: "image/character/ol_feiyi.jpg",
		dieAudios: ["ol_feiyi"],
	},
	old_ol_pengyang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["olxiaofan", "old_oltuishi", "nzry_cunmu"],
		img: "image/character/ol_pengyang.jpg",
		dieAudios: ["ol_pengyang"],
		tempname: ["ol_pengyang"],
	},
	old_sp_sunce: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olliantao"],
		img: "image/character/sp_sunce.jpg",
		dieAudios: ["sp_sunce"],
	},
	old_ol_yufan: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["old_olzongxuan", "old_olzhiyan"],
		img: "image/character/re_yufan.jpg",
		dieAudios: ["re_yufan"],
		tempname: ["re_yufan"],
	},
	old_ol_chengpu: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["dclihuo", "old_olchunlao"],
		img: "image/character/ol_chengpu.jpg",
		dieAudios: ["ol_chengpu"],
	},
	old_zhugejin: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["olhuanshi", "olhongyuan", "olmingzhe"],
		img: "image/character/zhugejin.jpg",
		dieAudios: ["zhugejin"],
		names: "诸葛|瑾",
	},
	old_ruiji: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["old_qiaoli", "old_qingliang"],
		img: "image/character/ruiji.jpg",
		dieAudios: ["ruiji"],
	},
	old_xurong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["old_xionghuo", "old_shajue"],
		img: "image/character/xurong.jpg",
		dieAudios: ["xurong"],
	},
	old_ol_qianzhao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["olweifu", "old_olkuansai"],
		img: "image/character/ol_qianzhao.jpg",
		dieAudios: ["ol_qianzhao"],
	},
	old_ol_sb_dongzhuo: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["old_olguanbian", "old_olxiongni", "old_olfengshang", "old_olzhibin"],
		img: "image/character/ol_sb_dongzhuo.jpg",
		dieAudios: ["ol_sb_dongzhuo"],
		isZhugong: true,
		tempname: ["ol_sb_dongzhuo"],
	},
	old_ol_nanhualaoxian: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["old_olqingshu", "old_olshoushu", "old_olhedao"],
		img: "image/character/ol_nanhualaoxian.jpg",
		dieAudios: ["ol_nanhualaoxian"],
		names: "庄|周",
	},
	oldx_ol_sb_dengai: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["oldx_olsbjiewan", "olsbpixian"],
		img: "image/character/ol_sb_dengai.jpg",
		dieAudios: ["ol_sb_dengai"],
	},
	old_ol_wangyi: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["old_olzhenlie", "olmiji"],
		img: "image/character/ol_wangyi.jpg",
		dieAudios: ["ol_wangyi"],
	},
	old_ol_xuelingyun: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["old_olsiqi", "olqiaozhi"],
		img: "image/character/ol_xuelingyun.jpg",
		dieAudios: ["ol_xuelingyun"],
	},
	old_ol_sb_yl_luzhi: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["old_olsibing", "old_olliance"],
		img: "image/character/ol_sb_yl_luzhi.jpg",
		dieAudios: ["ol_sb_yl_luzhi"],
	},
	old_ol_liubiao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["old_olzishou", "old_olzongshi"],
		img: "image/character/ol_liubiao.jpg",
		dieAudios: ["ol_liubiao"],
	},
	old_kongshu: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["olleiluan", "olfuchao"],
		img: "image/character/kongshu.jpg",
		dieAudios: ["kongshu"],
	},
	old_ol_madai: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["mashu", "old_olqianxi"],
		img: "image/character/ol_madai.jpg",
		dieAudios: ["kol_madai"],
	},
	old_strong_caochong: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["strongduanti", "stronglianwu", "olchengxiang"],
		img: "image/character/strong_caochong.jpg",
		dieAudios: ["strong_caochong"],
		tempname: ["strong_caochong"],
	},
	old_ol_sb_dengai: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 5,
		skills: ["old_olsbjigu", "old_olsbjiewan"],
		img: "image/character/ol_sb_dengai.jpg",
		dieAudios: ["ol_sb_dengai"],
	},
	old_dm_sunquan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["old_olquanyu", "old_oltianen", "old_olqiangang"],
		img: "image/character/dm_sunquan.jpg",
		dieAudios: ["dm_sunquan"],
	},
	old_ol_yangfeng: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["oldx_oljiawei", "old_olqujia"],
		img: "image/character/ol_yangfeng.jpg",
		dieAudios: ["ol_yangfeng"],
	},
	old_ol_sb_zhangrang: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["old_olsblucun", "old_olsbtuisheng"],
		trashBin: ["sex:male_castrated"],
		img: "image/character/ol_sb_zhangrang.jpg",
		dieAudios: ["ol_sb_zhangrang"],
		tempname: ["ol_sb_zhangrang"],
	},

	//十周年
	old_re_zhangchunhua: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["rejueqing", "reshangshi"],
		img: "image/character/re_zhangchunhua.jpg",
		dieAudios: ["re_zhangchunhua"],
	},
	old_re_caorui: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["huituo", "remingjian", "rexingshuai"],
		img: "image/character/re_caorui.jpg",
		dieAudios: ["re_caorui"],
		isZhugong: true,
	},
	old_dc_xushu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["old_rezhuhai", "xsqianxin"],
		img: "image/character/dc_xushu.jpg",
		dieAudios: ["dc_xushu"],
	},
	old_yuechen: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["old_dcporui", "old_dcgonghu"],
		img: "image/character/yuechen.jpg",
		dieAudios: ["yuechen"],
	},
	old_ruanyu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["xingzuo", "old_miaoxian"],
		img: "image/character/ruanyu.jpg",
		dieAudios: ["ruanyu"],
	},
	old_bailingyun: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["old_dclinghui", "dcxiace", "dcyuxin"],
		img: "image/character/bailingyun.jpg",
		dieAudios: ["bailingyun"],
	},
	old_dc_liuli: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["old_dcfuli", "dcdehua"],
		img: "image/character/dc_liuli.jpg",
		dieAudios: ["dc_liuli"],
	},
	old_yue_miheng: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["old_dcjigu", "dcsirui"],
		img: "image/character/yue_miheng.jpg",
		dieAudios: ["yue_miheng"],
	},
	old_wu_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 7,
		skills: ["dcjincui", "old_dcqingshi", "old_dczhizhe"],
		img: "image/character/wu_zhugeliang.jpg",
		dieAudios: ["wu_zhugeliang"],
		names: "诸葛|亮",
	},
	old_wu_guanyu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["old_dcjuewu", "old_dcwuyou", "old_dcyixian"],
		img: "image/character/wu_guanyu.jpg",
		dieAudios: ["wu_guanyu"],
	},
	old_wu_huangfusong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["old_dcchaozhen", "old_dclianjie", "old_dcjiangxian"],
		img: "image/character/wu_huangfusong.jpg",
		dieAudios: ["wu_huangfusong"],
		names: "皇甫|嵩",
	},
	old_dc_shen_huatuo: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["old_jingyu", "lvxin", "huandao"],
		img: "image/character/dc_shen_huatuo.jpg",
		dieAudios: ["dc_shen_huatuo"],
		groupInGuozhan: "qun",
	},
	old_xunyuxunyou: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["old_zhinang", "old_gouzhu"],
		img: "image/character/xunyuxunyou.jpg",
		dieAudios: ["xunyuxunyou"],
		names: "荀|彧-荀|攸",
	},
	old_zhugejing: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dcyanzuo", "dczuyin", "old_dcpijian"],
		img: "image/character/zhugejing.jpg",
		dieAudios: ["zhugejing"],
		names: "诸葛|京",
	},
	old_xin_zhonghui: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["old_xinquanji", "old_xinzili"],
		img: "image/character/xin_zhonghui.jpg",
		dieAudios: ["xin_zhonghui"],
		clans: ["颍川钟氏"],
	},
	old_yj_majun: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["gongqiao", "old_jingyi"],
		img: "image/character/yj_majun.jpg",
		dieAudios: ["yj_majun"],
	},
	old_star_fazheng: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["starzhiji", "old_staranji"],
		img: "image/character/star_fazheng.jpg",
		dieAudios: ["star_fazheng"],
	},
	old_star_dingfeng: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["old_stardangchen", "starjianyu"],
		img: "image/character/star_dingfeng.jpg",
		dieAudios: ["star_dingfeng"],
	},
	old_pangfengyi: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["old_dcyitong", "old_dcpeiniang"],
		img: "image/character/pangfengyi.jpg",
		dieAudios: ["pangfengyi"],
	},
	old_dc_sp_zhurong: {
		sex: "female",
		group: "qun",
		hp: 4,
		skills: ["old_dcremanhou", "old_dcretanluan"],
		img: "image/character/dc_sp_zhurong.jpg",
		dieAudios: ["dc_sp_zhurong"],
		names: "null|null",
	},
	old_v_sunquan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["old_dcwoheng", "old_dcjizheng"],
		img: "image/character/v_sunquan.jpg",
		dieAudios: ["v_sunquan"],
	},
	old_liujinliupei: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["old_dcllqixin", "dcjiusi"],
		img: "image/character/liujinliupei.jpg",
		dieAudios: ["liujinliupei"],
		names: "刘|衿-刘|佩",
	},
	old_dc_sb_xunyu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dcsbbizuo", "old_dcsbshimou", "dcsbxianshi"],
		img: "image/character/dc_sb_xunyu.jpg",
		dieAudios: ["dc_sb_xunyu"],
	},
	old_dc_xiahouxuan: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dcboxuan", "old_dcyizheng", "old_dcguilin"],
		img: "image/character/dc_xiahouxuan.jpg",
		dieAudios: ["dc_xiahouxuan"],
		names: "夏侯|玄",
	},
	old_dc_zhugejun: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["dcgengdu", "old_dcgumai"],
		img: "image/character/dc_zhugejun.jpg",
		dieAudios: ["dc_zhugejun"],
	},
	old_dc_tengfanglan: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["dcluochong", "old_dcaichen"],
		img: "image/character/dc_tengfanglan.jpg",
		dieAudios: ["dc_tengfanglan"],
	},
	old_dc_sb_dengai: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["old_dcsbzhouxi", "old_dcsbshijin"],
		img: "image/character/dc_sb_dengai.jpg",
		dieAudios: ["dc_sb_dengai"],
	},
	old_renwan: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["old_dcjuanji", "old_dcrenshuang"],
		img: "image/character/renwan.jpg",
		dieAudios: ["renwan"],
	},
	old_lukai: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["old_bushi", "old_zhongzhuang"],
		img: "image/character/lukai.jpg",
		dieAudios: ["lukai"],
	},
	oldx_zhangqiying: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["old_falu", "old_dianhua", "old_zhenyi"],
		img: "image/character/zhangqiying.jpg",
		dieAudios: ["zhangqiying"],
	},
	old_v_machao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["old_dczhongtao", "dcjizhan"],
		img: "image/character/v_machao.jpg",
		dieAudios: ["v_machao"],
	},
	old_wufu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dczhonge", "dcjuekai"],
		img: "image/character/wufu.jpg",
		dieAudios: ["wufu"],
	},
	old_dc_sb_hulie: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["old_dcsbchuanyu", "old_dcsbyitou"],
		img: "image/character/dc_sb_hulie.jpg",
		dieAudios: ["dc_sb_hulie"],
	},
	old_chengui: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["old_yingtu", "old_congshi"],
		img: "image/character/chengui.jpg",
		dieAudios: ["chengui"],
	},
	old_dc_sb_luxun: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["old_dcsbjunmou", "old_dcsbzhanyan"],
		img: "image/character/dc_sb_luxun.jpg",
		dieAudios: ["dc_sb_luxun"],
	},
	old_dc_sb_xuyou: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["old_dcsbmoyou", "dcsbshiao"],
		img: "image/character/dc_sb_xuyou.jpg",
		dieAudios: ["dc_sb_xuyou"],
	},
	old_dc_weifeng: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dchuozhong", "old_dczhuguo"],
		img: "image/character/dc_weifeng.jpg",
		dieAudios: ["dc_weifeng"],
	},
	old_v_sunce: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["old_dczhifeng", "old_dcweijing"],
		img: "image/character/v_sunce.jpg",
		dieAudios: ["v_sunce"],
	},
	old_dc_shen_sunquan: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["old_dccangming", "old_dcchouxi", "old_dcjichao"],
		img: "image/character/dc_shen_sunquan.jpg",
		dieAudios: ["dc_shen_sunquan"],
		groupInGuozhan: "wu",
	},
	old_hansong: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dcyinbi", "old_dcshuaiyan"],
		img: "image/character/hansong.jpg",
		dieAudios: ["hansong"],
	},
	old_liuyijun: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["dcdulu", "old_dcfuji"],
		img: "image/character/liuyijun.jpg",
		dieAudios: ["liuyijun"],
	},
	//海外
	old_tw_huojun: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["twsidai", "old_twjieyu"],
		img: "image/character/tw_huojun.jpg",
		dieAudios: ["tw_huojun"],
	},
	old_tw_guohuai: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["old_twjingce", "old_yuzhang"],
		img: "image/character/tw_guohuai.jpg",
		dieAudios: ["tw_guohuai"],
	},
	oldx_quancong: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["old_zhenshan"],
		img: "image/character/quancong.jpg",
		dieAudios: ["quancong"],
	},
	old_tw_baoxin: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["old_twmutao", "old_twyimou"],
		img: "image/character/tw_baoxin.jpg",
		dieAudios: ["tw_baoxin"],
	},
	old_tw_zhangmancheng: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twfengji", "twyiju", "old_twbudao"],
		img: "image/character/tw_zhangmancheng.jpg",
		dieAudios: ["tw_zhangmancheng"],
	},
	old_tw_guanqiujian: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["twzhengrong", "twhongju"],
		img: "image/character/tw_guanqiujian.jpg",
		dieAudios: ["tw_guanqiujian"],
		names: "毌丘|俭",
	},
	old_tw_niufudongxie: {
		sex: "double",
		group: "qun",
		hp: 4,
		skills: ["old_twjuntun", "old_twxiongxi", "twxiafeng"],
		img: "image/character/tw_niufudongxie.jpg",
		dieAudios: ["tw_niufudongxie"],
		names: "牛|辅-董|翓",
	},
	old_xia_guanyu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["old_twzhongyi", "twchue"],
		img: "image/character/xia_guanyu.jpg",
		dieAudios: ["xia_guanyu"],
	},
	old_xia_zhaoe: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["old_twyanshi", "old_twrenchou"],
		img: "image/character/xia_zhaoe.jpg",
		dieAudios: ["xia_zhaoe"],
	},
	old_huan_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 4,
		skills: ["twbeiding", "twjielv", "old_twhunyou"],
		img: "image/character/huan_zhugeliang.jpg",
		dieAudios: ["huan_zhugeliang"],
		names: "诸葛|亮",
	},
	old_huan_weiyan: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["twqiji", "old_twpiankuang"],
		img: "image/character/huan_weiyan.jpg",
		dieAudios: ["huan_weiyan"],
	},
	old_huan_zhugeguo: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["old_rexianyuan", "twlingyin"],
		img: "image/character/huan_zhugeguo.jpg",
		dieAudios: ["huan_zhugeguo"],
	},
	old_tw_shen_lvmeng: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["old_twgongxin", "old_twshelie"],
		img: "image/character/tw_shen_lvmeng.jpg",
		dieAudios: ["shen_lvmeng"],
		groupInGuozhan: "wu",
	},
	old_huan_caoang: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 4,
		skills: ["old_twchihui", "old_twfuxi"],
		img: "image/character/huan_caoang.jpg",
		dieAudios: ["huan_caoang"],
	},
	old_tw_gexuan: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["old_twdanfa", "old_twlingbao", "twsidao"],
		img: "image/character/tw_gexuan.jpg",
		dieAudios: ["tw_gexuan"],
	},
	old_jsrg_huangfusong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twguanhuo", "old_twjuxia"],
		img: "image/character/jsrg_huangfusong.jpg",
		dieAudios: ["jsrg_huangfusong"],
		names: "皇甫|嵩",
	},
	old_yinfuren: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["old_dcyingyu", "old_dcyongbi"],
		img: "image/character/yinfuren.jpg",
		dieAudios: ["yinfuren"],
		names: "尹|null",
	},
	old_tw_jiangji: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["twjichou", "old_twjilun"],
		img: "image/character/tw_jiangji.jpg",
		dieAudios: ["tw_jiangji"],
	},
	old_tw_zhanghong: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["old_twquanqian", "old_twrouke"],
		img: "image/character/tw_zhanghong.jpg",
		dieAudios: ["tw_zhanghong"],
	},
	old_tw_zhangzhao: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["twlijian", "old_twchungang"],
		img: "image/character/tw_zhangzhao.jpg",
		dieAudios: ["tw_zhangzhao"],
	},
	old_tw_huangfusong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["old_twtaoluan", "old_twshiji", "old_twzhengjun"],
		img: "image/character/tw_huangfusong.jpg",
		dieAudios: ["sp_huangfusong"],
	},
	//其他
	diy_zhujun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["xinyangjie", "diy_juxiang", "houfeng"],
		img: "image/character/sp_zhujun.jpg",
	},
	diy_liaohua: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["redangxian", "diy_fuli"],
		img: "image/character/xin_liaohua.jpg",
	},
	diy_zhangfei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["diy_paoxiao", "diy_tishen"],
		img: "image/character/re_zhangfei.jpg",
	},
	//改
	wangtaowangyue: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["huguan", "yaopei", "mingluan"],
		dieAudios: ["ext:星之梦/audio/die/wangtaowangyue1.mp3", "ext:星之梦/audio/die/wangtaowangyue2.mp3"],
	},
	lm_old_caocao: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["lmjunkguixin", "feiying"],
		img: "image/character/old_caocao.jpg",
		dieAudios: ["old_caocao"],
	},

	//神武
	sw_guanyu: {
		sex: "male",
		group: "shen",
		hp: 5,
		skills: ["wushen", "new_wuhun", "shenwuzaishi"],
		img: "image/character/shen_guanyu.jpg",
		dieAudios: ["shen_guanyu"],
		groupInGuozhan: "shu",
	},
	sw_lvmeng: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["shelie", "gongxin", "shenwuzaishi"],
		img: "image/character/shen_lvmeng.jpg",
		dieAudios: ["shen_lvmeng"],
		groupInGuozhan: "wu",
	},
	sw_zhugeliang: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["qixing", "kuangfeng", "dawu", "shenwuzaishi"],
		img: "image/character/shen_zhugeliang.jpg",
		dieAudios: ["shen_zhugeliang"],
		groupInGuozhan: "shu",
		names: "诸葛|亮",
	},
	sw_zhouyu: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["yeyan", "miniqinyin", "shenwuzaishi"],
		img: "image/character/shen_zhouyu.jpg",
		dieAudios: ["shen_zhouyu"],
		groupInGuozhan: "wu",
	},
	sw_simayi: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["renjie", "sbaiyin", "lianpo", "shenwuzaishi"],
		img: "image/character/shen_simayi.jpg",
		dieAudios: ["shen_simayi"],
		groupInGuozhan: "wei",
		names: "司马|懿",
	},
	sw_zhaoyun: {
		sex: "male",
		group: "shen",
		hp: 2,
		skills: ["xinjuejing", "relonghun", "shenwuzaishi"],
		img: "image/character/shen_zhaoyun.jpg",
		dieAudios: ["shen_zhaoyun"],
		groupInGuozhan: "shu",
	},
	sw_caocao: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["guixin", "feiying", "shenwuzaishi"],
		img: "image/character/shen_caocao.jpg",
		dieAudios: ["shen_caocao"],
		groupInGuozhan: "wei",
	},
	sw_lvbu: {
		sex: "male",
		group: "shen",
		hp: 5,
		skills: ["baonu", "wumou", "ol_wuqian", "ol_shenfen", "shenwuzaishi"],
		img: "image/character/shen_lvbu.jpg",
		dieAudios: ["shen_lvbu"],
		groupInGuozhan: "qun",
	},
	sw_liubei: {
		sex: "male",
		group: "shen",
		hp: 6,
		skills: ["nzry_longnu", "nzry_jieying", "shenwuzaishi"],
		img: "image/character/shen_liubei.jpg",
		dieAudios: ["shen_liubei"],
		groupInGuozhan: "shu",
	},
	sw_luxun: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["nzry_junlve", "nzry_cuike", "nzry_dinghuo", "shenwuzaishi"],
		img: "image/character/shen_luxun.jpg",
		dieAudios: ["shen_luxun"],
		groupInGuozhan: "wu",
	},
	sw_zhangliao: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["drlt_duorui", "lmzhiti", "shenwuzaishi"],
		img: "image/character/shen_zhangliao.jpg",
		dieAudios: ["shen_zhangliao"],
		groupInGuozhan: "wei",
	},
	sw_ganning: {
		sex: "male",
		group: "shen",
		hp: 3,
		maxHp: 6,
		skills: ["drlt_poxi", "drlt_jieying", "shenwuzaishi"],
		img: "image/character/shen_ganning.jpg",
		dieAudios: ["shen_ganning"],
		groupInGuozhan: "wu",
	},
	sw_caopi: {
		sex: "male",
		group: "shen",
		hp: 5,
		skills: ["chuyuan", "dengji", "shenwuzaishi"],
		img: "image/character/shen_caopi.jpg",
		dieAudios: ["shen_caopi"],
		groupInGuozhan: "wei",
	},
	sw_zhenji: {
		sex: "female",
		group: "shen",
		hp: 4,
		skills: ["shenfu", "qixian", "shenwuzaishi"],
		img: "image/character/shen_zhenji.jpg",
		dieAudios: ["shen_zhenji"],
		groupInGuozhan: "wei",
	},
	sw_zhangjiao: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["yizhao", "sijun", "tianjie", "shenwuzaishi"],
		img: "image/character/shen_zhangjiao.jpg",
		dieAudios: ["shen_zhangjiao"],
		groupInGuozhan: "qun",
	},
	sw_diaochan: {
		sex: "female",
		group: "shen",
		hp: 3,
		skills: ["minimeihun", "minihuoxin", "shenwuzaishi"],
		img: "image/character/shen_diaochan.jpg",
		dieAudios: ["shen_diaochan"],
		groupInGuozhan: "qun",
	},
	sw_tw_guanyu: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["twwushen", "twwuhun", "shenwuzaishi"],
		img: "image/character/tw_shen_guanyu.jpg",
		dieAudios: ["tw_shen_guanyu"],
		groupInGuozhan: "shu",
	},
	sw_tw_lvmeng: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["old_twshelie", "old_twgongxin", "shenwuzaishi"],
		img: "image/character/tw_shen_lvmeng.jpg",
		dieAudios: ["shen_lvmeng"],
		groupInGuozhan: "wu",
	},
	sw_wechat_zhugeliang: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["wechatqixing", "wechatjifeng", "wechattianfa", "shenwuzaishi"],
		dieAudios: ["shen_zhugeliang"],
		groupInGuozhan: "shu",
		names: "诸葛|亮",
	},

	lm_xurong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["old_xionghuo", "old_shajue", "xr_huyi"],
		img: "image/character/xurong.jpg",
		dieAudios: ["xurong"],
	},

	//其他
	unlock_dongzhao: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["olxianlve", "olzaowang"],
		img: "image/character/ol_dongzhao.jpg",
		dieAudios: ["ol_dongzhao"],
	},
	unlock_tianchuan: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["pshuying", "psqianjing", "psbianchi"],
		img: "image/character/yj_tianchuan.jpg",
	},
	lm_jikang: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["qingxian", "fh_juexiang"],
		img: "image/character/jikang.jpg",
		dieAudios: ["jikang"],
	},

	//十常侍
	lm_shichangshi: {
		sex: "male",
		group: "qun",
		hp: 1,
		skills: ["scstaoluan", "scschiyan", "scszimou", "scspicai", "scsyaozhuo", "scsxiaolu", "scskuiji", "scschihe", "scsniqu", "scsanruo"],
		img: "image/character/shichangshi.jpg",
		dieAudios: ["shichangshi"],
		trashBin: ["sex:male_castrated"],
		names: "张|让-赵|忠-孙|璋-毕|岚-夏|恽-韩|悝-栗|嵩-段|珪-郭|胜-高|望",
	},
	lm_zhangrang: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["scstaoluan"],
		img: "image/character/scs_zhangrang.jpg",
		dieAudios: ["scs_zhangrang"],
		trashBin: ["sex:male_castrated"],
	},
	lm_zhaozhong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["scschiyan"],
		img: "image/character/scs_zhaozhong.jpg",
		dieAudios: ["scs_zhaozhong"],
		trashBin: ["sex:male_castrated"],
	},
	lm_sunzhang: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["scszimou"],
		img: "image/character/scs_sunzhang.jpg",
		dieAudios: ["scs_sunzhang"],
		trashBin: ["sex:male_castrated"],
	},
	lm_bilan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["scspicai"],
		img: "image/character/scs_bilan.jpg",
		dieAudios: ["scs_bilan"],
		trashBin: ["sex:male_castrated"],
	},
	lm_xiayun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["scsyaozhuo"],
		img: "image/character/scs_xiayun.jpg",
		dieAudios: ["scs_xiayun"],
		trashBin: ["sex:male_castrated"],
	},
	lm_hankui: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["scsxiaolu"],
		img: "image/character/scs_hankui.jpg",
		dieAudios: ["scs_hankui"],
		trashBin: ["sex:male_castrated"],
	},
	lm_lisong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["scskuiji"],
		img: "image/character/scs_lisong.jpg",
		dieAudios: ["scs_lisong"],
		trashBin: ["sex:male_castrated"],
	},
	lm_duangui: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["scschihe"],
		img: "image/character/scs_duangui.jpg",
		dieAudios: ["scs_duangui"],
		trashBin: ["sex:male_castrated"],
	},
	lm_guosheng: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["scsniqu"],
		img: "image/character/scs_guosheng.jpg",
		dieAudios: ["scs_guosheng"],
		trashBin: ["sex:male_castrated"],
	},
	lm_gaowang: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["scsanruo"],
		img: "image/character/scs_gaowang.jpg",
		dieAudios: ["scs_gaowang"],
		trashBin: ["sex:male_castrated"],
	},
	//头像
	aaAronaPurana: {
		sex: "",
		group: "shen",
		hp: 9,
		skills: [],
		isUnseen: true,
	},
	aaAqua: {
		sex: "",
		group: "shen",
		hp: 9,
		skills: [],
		isUnseen: true,
	},
	abAqua: {
		sex: "",
		group: "shen",
		hp: 9,
		skills: [],
		isUnseen: true,
	},
	aamomo: {
		sex: "",
		group: "shen",
		hp: 9,
		skills: [],
		isUnseen: true,
	},
	aamidori: {
		sex: "",
		group: "shen",
		hp: 9,
		skills: [],
		isUnseen: true,
	},
	aaNina: {
		sex: "",
		group: "shen",
		hp: 9,
		skills: [],
		isUnseen: true,
	},
	aahikari: {
		sex: "",
		group: "shen",
		hp: 9,
		skills: [],
		isUnseen: true,
	},
	aanozomi: {
		sex: "",
		group: "shen",
		hp: 9,
		skills: [],
		isUnseen: true,
	},
	aaKotone: {
		sex: "",
		group: "shen",
		hp: 9,
		skills: [],
		isUnseen: true,
	},
};
export default characters;
