import { lib, game, ui, get, ai, _status } from "../../../noname.js"
let lmCharacter = {//武将信息

    //手杀
    old_new_simayi: ["male", "shen", 4, ["old_jilin", "old_yingyou", "old_yingtian"], ["character:new_simayi", "die:new_simayi", "wei", "name:司马|懿"]],
    old_shen_lusu: ["male", "shen", 3, ["old_tamo", "old_dingzhou", "old_zhimeng"], ["character:shen_lusu", "die:shen_lusu", "wu"]],
    old_mb_jushou: ["male", "qun", 3, ["old_xinjianying", "xinshibei"], ["character:xin_jushou", "die:xin_jushou"]],
    old_mb_zhuzhi: ["male", "wu", 4, ["old_sbanguo"], ["character:xin_zhuzhi", "die:xin_zhuzhi"]],
    old_mb_sp_zhenji: ["female", "qun", 3, ["old_mbbojian", "old_mbjiwei"], ["character:mb_sp_zhenji", "die:mb_sp_zhenji"]],
    old_fuqian: ["male", "shu", 4, ["old_jueyong", "old_poxiang"], ["character:fuqian", "die:fuqian"]],
    old_mb_guozhao: ["female", "wei", 3, ["old_yichong", "old_wufei"], ["character:xin_guozhao", "die:xin_guozhao"]],
    old_mb_chengui: ["male", "qun", 3, ["old_guimou", "zhouxian"], ["character:mb_chengui", "die:mb_chengui"]],
    old_yangfu: ["male", "wei", 4, ["oldx_jiebing", "old_hannan"], ["character:yangfu", "die:yangfu"]],
    old_lizhaojiaobo: ["male", "wei", 4, ["old_mbzuoyou", "old_mbshishou"], ["character:lizhaojiaobo", "die:lizhaojiaobo", "name:李|昭-焦|伯"]],
    old_wangling: ["male", "wei", 4, ["mouli", "zifu"], ["character:wangling", "die:wangling", "clan:太原王氏"]],
    old_sp_wangshuang: ["male", "wei", 4, ["yiyong", "old_shanxie"], ["character:sp_wangshuang", "die:sp_wangshuang"]],
    old_wujing: ["male", "wu", 4, ["heji", "old_liubing"], ["character:wujing", "die:wujing"]],
    old_sp_xinpi: ["male", "wei", 3, ["old_spyinju", "spchijie"], ["character:sp_xinpi", "die:sp_xinpi"]],
    old_qiaogong: ["male", "wu", 3, ["old_yizhu", "luanchou"], ["character:qiaogong", "die:qiaogong", "name:桥|null"]],
    old_sp_lvfan: ["male", "wu", 3, ["spdiaodu", "spdiancai", "spyanji"], ["character:sp_lvfan", "die:sp_lvfan"]],
    old_xin_zhangzhongjing: ["male", "qun", 3, ["jishi", "liaoyi", "binglun"], ["character:zhangzhongjing", "die:zhangzhongjing"]],
    old_sp_zhujun: ["male", "qun", 4, ["yangjie", "zjjuxiang", "houfeng"], ["character:sp_zhujun", "die:sp_zhujun"]],
    old_yj_weiyan: ["male", "qun", 5, ["mbguli", "mbaosi"], ["character:yj_weiyan", "die:yj_weiyan"]],
    old_yj_zhoubuyi: ["male", "wei", 3, ["old_mbhuiyao", "old_mbquesong"], ["character:yj_zhoubuyi", "die:yj_zhoubuyi"]],
    old_shenpei: ["male", "qun", 3, ["shouye", "liezhi"], ["character:shenpei", "die:shenpei"]],
    old_mb_sp_guanqiujian: ["male", "wei", 4, ["old_mbcuizhen", "mbkuili"], ["character:mb_sp_guanqiujian", "die:mb_sp_guanqiujian", "name:毌丘|俭"]],
    old_mb_wangjing: ["male", "wei", 3, ["mbzujin", "old_mbjiejian"], ["character:mb_wangjing", "die:mb_wangjing"]],
    oldx_sp_jianggan: ["male", "wei", 3, ["old_spdaoshu", "spdaizui"], ["character:sp_jianggan", "die:sp_jianggan"]],
    old_liwei: ["male", "shu", 4, ["old_jiaohua"], ["character:liwei", "die:tw_liwei"]],
    old_friend_xushu: ["male", "qun", 3, ["old_friendxiaxing", "friendqihui", "friendxushugongli"], ["character:friend_xushu", "die:friend_xushu"]],
    old_pot_lougui: ["male", "wei", 3, ["potguansha", "old_potjiyu"], ["character:pot_lougui", "die:pot_lougui"]],
    old_sb_huangyueying: ["female", "shu", 3, ["sbjizhi", "old_sbqicai"], ["character:sb_huangyueying", "die:sb_huangyueying"]],
    old_sb_huangzhong: ["male", "shu", 4, ["old_sbliegong"], ["character:sb_huangzhong", "die:sb_huangzhong"]],
    old_sb_gongsunzan: ["male", "qun", 4, ["sbyicong", "old_sbqiaomeng"], ["character:sb_gongsunzan", "die:sb_gongsunzan", "name:公孙|瓒"]],
    old_sb_sunquan: ["male", "wu", 4, ["old_sbzhiheng", "old_sbtongye", "sbjiuyuan"], ["character:sb_sunquan", "die:sb_sunquan", "zhu"]],
    old_sb_huanggai: ["male", "wu", "2/4/2", ["sbkurou", "sbzhaxiang"], ["character:sb_huanggai", "die:sb_huanggai"]],
    old_sb_ganning: ["male", "wu", 4, ["old_sbqixi", "old_sbfenwei"], ["character:sb_ganning", "die:sb_ganning"]],
    old_sb_xiaoqiao: ["female", "wu", 3, ["old_sbtianxiang", "xinhongyan"], ["character:sb_xiaoqiao", "die:sb_xiaoqiao", "name:桥|null"]],
    old_sb_daqiao: ["female", "wu", 3, ["old_sbguose", "sbliuli"], ["character:sb_daqiao", "die:sb_daqiao", "name:桥|null"]],
    old_sb_sunce: ["male", "wu", 4, ["sbjiang", "old_sbhunzi", "sbzhiba"], ["character:sb_sunce", "die:sb_sunce", "zhu"]],
    old_sb_sp_zhugeliang: ["male", "shu", 3, ["old_sbhuoji", "old_sbkanpo"], ["character:sb_sp_zhugeliang", "die:sb_sp_zhugeliang", "name:诸葛|亮"]],
    old_sb_zhugeliang: ["male", "shu", 3, ["old_sbguanxing", "old_sbkongcheng"], ["character:sb_zhugeliang", "die:sb_zhugeliang", "name:诸葛|亮"]],
    oldx_sb_sp_zhugeliang: ["male", "shu", 3, ["oldx_sbhuoji", "oldx_sbkanpo"], ["character:sb_sp_zhugeliang", "die:sb_sp_zhugeliang", "name:诸葛|亮"]],
    oldx_sb_zhugeliang: ["male", "shu", 3, ["oldx_sbguanxing", "oldx_sbkongcheng"], ["character:sb_zhugeliang", "die:sb_zhugeliang", "name:诸葛|亮"]],
    old_sb_menghuo: ["male", "shu", 4, ["sbhuoshou", "old_sbzaiqi"], ["character:sb_menghuo", "die:sb_menghuo", "doublegroup:shu:qun"]],
    old_sb_zhurong: ["female", "shu", 4, ["old_sblieren", "old_sbjuxiang"], ["character:sb_zhurong", "die:sb_zhurong", "doublegroup:shu:qun"]],
    old_sb_guanyu: ["male", "shu", 4, ["old_sbwusheng", "sbyijue"], ["character:sb_guanyu", "die:sb_guanyu"]],
    old_sb_zhaoyun: ["male", "shu", 4, ["old_sblongdan", "old_sbjizhu"], ["character:sb_zhaoyun", "die:sb_zhaoyun"]],
    old_sb_fazheng: ["male", "shu", 3, ["old_sbxuanhuo", "old_sbenyuan"], ["character:sb_fazheng", "die:sb_fazheng"]],
    old_sb_xuhuang: ["male", "wei", 4, ["old_sbduanliang", "sbshipo"], ["character:sb_xuhuang", "die:sb_xuhuang"]],
    old_sb_yuanshao: ["male", "qun", 4, ["old_sbluanji", "old_sbxueyi"], ["character:sb_yuanshao", "die:sb_yuanshao", "zhu"]],
    // old_sb_zhangjiao: ["male", "qun", 3, ["old_sbleiji", "old_sbguidao", "old_sbhuangtian"], ["character:sb_zhangjiao", "die:sb_zhangjiao", "zhu"]],
    old_sb_huaxiong: ["male", "qun", "4/4/5", ["new_reyaowu", "sbyangwei"], ["character:sb_huaxiong", "die:sb_huaxiong"]],
    old_sb_handang: ["male", "wu", 4, ["sbgongqi", "old_sbjiefan"], ["character:sb_handang", "die:sb_handang"]],
    // old_sb_caopi: ["male", "wei", 3, ["old_sbxingshang", "old_sbfangzhu", "old_sbsongwei"], ["die:ext:星之梦/audio/die:true", "zhu"]],
    old_sb_jiaxu: ["male", "qun", 3, ["old_sbwansha", "old_sbluanwu", "old_sbweimu"], ["character:sb_jiaxu", "die:sb_jiaxu"]],
    old_sb_zhugejin: ["male", "wu", 3, ["old_sbhuanshi", "old_sbhongyuan", "old_sbmingzhe"], ["character:sb_zhugejin", "die:sb_zhugejin", "name:诸葛|瑾"]],
    old_sb_zhangliao: ["male", "wei", 4, ["old_sbtuxi", "old_sbdengfeng"], ["character:sb_zhangliao", "die:sb_zhangliao"]],
    old_sb_guojia: ["male", "wei", 3, ["sbtiandu", "old_sbyiji"], ["character:sb_guojia", "die:sb_guojia"]],
    old_sb_gaoshun: ["male", "qun", 4, ["old_sbxianzhen", "sbjinjiu"], ["character:sb_gaoshun", "die:sb_gaoshun"]],
    old_sb_luxun: ["male", "wu", 3, ["sbqianxun", "old_sblianying"], ["character:sb_luxun", "die:sb_luxun"]],
    old_sb_xiahouyuan: ["male", "wei", 4, ["sbshensu", "old_sbzhengzi"], ["character:sb_xiahouyuan", "die:sb_xiahouyuan", "name:夏侯|渊"]],
    old_sb_lvbu: ["male", "qun", 4, ["old_sbwushuang", "old_sbliyu"], ["character:sb_lvbu", "die:sb_lvbu"]],
    old_pot_taishici: ["male", "wu", 4, ["old_pothanzhan", "old_potzhanlie", "old_potzhenfeng"], ["character:pot_taishici", "die:pot_taishici", "太史|慈"]],
    old_pot_chendao: ["male", "shu", 4, ["old_potwanglie", "old_pothongyi"], ["character:pot_chendao", "die:pot_chendao"]],
    old_pot_yuji: ["male", "qun", 3, ["old_potdaozhuan", "old_potfuji"], ["character:pot_yuji", "die:pot_yuji"]],
    old_zhangbu: ["male", "wu", 4, ["old_mbchengxiong", "old_mbwangzhuang"], ["character:zhangbu", "die:zhangbu"]],
    old_wuke: ["female", "wu", 3, ["old_mbanda", "old_mbzhuguo"], ["character:wuke", "die:wuke", "吴|null"]],
    old_pot_weiyan: ["male", "shu", 4, ["old_potzhongao", "old_potzhuangshi", "potyinzhan"], ["character:pot_weiyan", "die:pot_weiyan"]],
    //OL
    oldx_clan_xuncai: ["female", "qun", 3, ["oldx_clanlieshi", "oldx_clandianzhan", "clanhuanyin", "clandaojie"], ["character:clan_xuncai", "die:clan_xuncai", "clan:颍川荀氏"]],
    old_clan_zhonghui: ["male", "wei", "3/4", ["old_clanyuzhi", "old_clanxieshu", "clanbaozu"], ["character:clan_zhonghui", "die:clan_zhonghui", "clan:颍川钟氏", "die:3"]],
    old_clan_hanrong: ["male", "qun", 3, ["old_lianhe", "old_huanjia", "old_xumin"], ["character:clan_hanrong", "die:clan_hanrong", "clan:颍川韩氏"]],
    old_clan_hanshao: ["male", "qun", 3, ["old_fangzhen", "old_liuju", "old_xumin"], ["character:clan_hanshao", "die:clan_hanshao", "clan:颍川韩氏"]],
    old_zhanghua: ["male", "jin", 3, ["olbihun", "olchuanwu", "oljianhe"], ["character:zhanghua", "die:zhanghua"]],
    old_yuanji: ["female", "wu", 3, ["dcmengchi", "dcjiexing"], ["character:yuanji", "die:yuanji", "name:袁|null"]],
    old_tengfanglan: ["female", "wu", 3, ["old_luochong", "old_aichen"], ["character:tengfanglan", "die:tengfanglan"]],
    old_dengzhong: ["male", "wei", 4, ["old_dzkanpo", "old_dzgengzhan"], ["character:dengzhong", "die:dengzhong"]],
    old_wangyan: ["male", "jin", 3, ["yangkuang", "old_cihuang", "old_sanku"], ["character:wangyan", "die:wangyan"]],
    old_ol_luyusheng: ["female", "wu", 3, ["old_olcangxin", "olrunwei"], ["character:ol_luyusheng", "die:ol_luyusheng"]],
    old_ol_hujinding: ["female", "shu", 3, ["olqingyuan", "old_olchongshen"], ["character:ol_hujinding", "die:ol_hujinding"]],
    old_ol_feiyi: ["male", "shu", 3, ["yanru", "old_hezhong"], ["character:ol_feiyi", "die:ol_feiyi"]],
    old_ol_pengyang: ["male", "shu", 3, ["olxiaofan", "old_oltuishi", "nzry_cunmu"], ["character:ol_pengyang", "die:ol_pengyang"]],
    old_sp_sunce: ["male", "qun", 4, ["olliantao"], ["character:sp_sunce", "die:sp_sunce"]],
    old_ol_yufan: ["male", "wu", 3, ["old_olzongxuan", "old_olzhiyan"], ["tempname:re_yufan", "character:ol_yufan", "die:re_yufan"]],
    old_zhugejin: ["male", "wu", 3, ["olhuanshi", "olhongyuan", "olmingzhe"], ["character:zhugejin", "die:zhugejin", "name:诸葛|瑾"]],
    old_ruiji: ["female", "wu", 3, ["old_qiaoli", "old_qingliang"], ["character:ruiji", "die:ruiji"]],
    old_xurong: ["male", "qun", 4, ["old_xionghuo", "old_shajue"], ["character:xurong", "die:xurong"]],
    old_ol_qianzhao: ["male", "wei", 4, ["olweifu", "old_olkuansai"], ["character:ol_qianzhao", "die:ol_qianzhao"]],
    old_ol_sb_dongzhuo: ["male", "qun", 5, ["old_olguanbian", "old_olxiongni", "old_olfengshang", "old_olzhibin"], ["character:ol_sb_dongzhuo", "ol_sb_dongzhuo", "zhu", "tempname:ol_sb_dongzhuo", "die:3"]],
    old_ol_nanhualaoxian: ["male", "qun", 4, ["old_olqingshu", "old_olshoushu", "old_olhedao"], ["character:ol_nanhualaoxian", "die:ol_nanhualaoxian", "name:庄|周"]],
    old_ol_sb_dengai: ["male", "wei", 4, ["old_olsbjiewan", "olsbpixian"], ["character:ol_sb_dengai", "die:ol_sb_dengai"]],
    old_ol_wangyi: ["female", "wei", 3, ["old_olzhenlie", "olmiji"], ["character:ol_wangyi", "die:ol_wangyi"]],
    old_ol_xuelingyun: ["female", "wei", 3, ["old_olsiqi", "olqiaozhi"], ["character:ol_xuelingyun", "die:ol_xuelingyun"]],
    old_ol_sb_yl_luzhi: ["male", "qun", 4, ["old_olsibing", "old_olliance"], ["character:ol_sb_yl_luzhi", "die:ol_sb_yl_luzhi"]],
    old_ol_liubiao: ["male", "qun", 3, ["old_olzishou", "old_olzongshi"], ["character:ol_liubiao", "die:ol_liubiao"]],
    old_kongshu: ["female", "qun", 3, ["olleiluan", "olfuchao"], ["character:kongshu", "die:kongshu"]],
    old_ol_madai: ["male", "shu", 4, ["mashu", "olqianxi"], ["character:ol_madai", "die:kol_madai"]],

    //十周年
    old_re_zhangchunhua: ["female", "wei", 3, ["rejueqing", "reshangshi"], ["character:re_zhangchunhua", "die:re_zhangchunhua"]],
    old_re_caorui: ["male", "wei", 3, ["huituo", "remingjian", "rexingshuai"], ["character:re_caorui", "re_caorui", "zhu"]],
    old_dc_xushu: ["male", "shu", 4, ["old_rezhuhai", "xsqianxin"], ["character:dc_xushu", "die:dc_xushu"]],
    old_yuechen: ["male", "wei", 4, ["old_dcporui", "old_dcgonghu"], ["character:yuechen", "die:yuechen"]],
    old_ruanyu: ["male", "wei", 3, ["xingzuo", "old_miaoxian"], ["character:ruanyu", "die:ruanyu"]],
    old_bailingyun: ["female", "wei", 3, ["oldx_dclinghui", "dcxiace", "dcyuxin"], ["character:bailingyun", "die:bailingyun"]],
    old_dc_liuli: ["male", "shu", 3, ["old_dcfuli", "old_dcdehua"], ["character:dc_liuli", "die:dc_liuli"]],
    old_yue_miheng: ["male", "qun", 3, ["old_dcjigu", "dcsirui"], ["character:yue_miheng", "die:yue_miheng"]],
    old_wu_zhugeliang: ["male", "shu", "4/7", ["dcjincui", "old_dcqingshi", "old_dczhizhe"], ["character:wu_zhugeliang", "die:wu_zhugeliang", "name:诸葛|亮"]],
    old_wu_guanyu: ["male", "shu", 4, ["old_dcjuewu", "old_dcwuyou", "old_dcyixian"], ["character:wu_guanyu", "die:wu_guanyu"]],
    old_wu_huangfusong: ["male", "qun", 4, ["old_dcchaozhen", "old_dclianjie", "old_dcjiangxian"], ["character:wu_huangfusong", "die:wu_huangfusong", "name:皇甫|嵩"]],
    old_dc_shen_huatuo: ["male", "shen", 3, ["old_jingyu", "lvxin", "huandao"], ["character:dc_shen_huatuo", "die:dc_shen_huatuo", "qun"]],
    old_xunyuxunyou: ["male", "wei", 3, ["old_zhinang", "old_gouzhu"], ["character:xunyuxunyou", "die:xunyuxunyou", "name:荀|彧-荀|攸"]],
    old_zhugejing: ["male", "qun", 4, ["dcyanzuo", "dczuyin", "old_dcpijian"], ["character:zhugejing", "die:zhugejing", "name:诸葛|京"]],
    old_xin_zhonghui: ["male", "wei", 4, ["old_xinquanji", "old_xinzili"], ["character:xin_zhonghui", "die:xin_zhonghui", "clan:颍川钟氏"]],
    old_yj_majun: ["male", "wei", 3, ["gongqiao", "old_jingyi"], ["character:yj_majun", "die:yj_majun"]],
    old_star_fazheng: ["male", "shu", 3, ["starzhiji", "old_staranji"], ["character:star_fazheng", "die:star_fazheng"]],
    old_star_dingfeng: ["male", "wu", 4, ["old_stardangchen", "starjianyu"], ["character:star_dingfeng", "die:star_dingfeng"]],
    old_pangfengyi: ["female", "shu", 3, ["old_dcyitong", "old_dcpeiniang"], ["character:pangfengyi", "die:pangfengyi"]],
    old_dc_sp_zhurong: ["female", "qun", 4, ["old_dcremanhou", "old_dcretanluan"], ["character:dc_sp_zhurong", "die:dc_sp_zhurong", "name:null|null"]],
    old_v_sunquan: ["male", "wu", 4, ["old_dcwoheng", "old_dcjizheng"], ["character:v_sunquan", "die:v_sunquan"]],
    old_liujinliupei: ["female", "wei", 3, ["old_dcllqixin", "dcjiusi"], ["character:liujinliupei", "die:liujinliupei", "刘|衿-刘|佩"]],
    old_dc_sb_xunyu: ["male", "wei", 3, ["dcsbbizuo", "old_dcsbshimou", "dcsbxianshi"], ["character:dc_sb_xunyu", "die:dc_sb_xunyu"]],
    old_dc_xiahouxuan: ["male", "wei", 3, ["dcboxuan", "old_dcyizheng", "old_dcguilin"], ["character:dc_xiahouxuan", "die:dc_xiahouxuan", "夏侯|玄"]],
    old_dc_zhugejun: ["male", "shu", 3, ["dcgengdu", "old_dcgumai"], ["character:dc_zhugejun", "die:dc_zhugejun"]],
    old_dc_tengfanglan: ["female", "wu", 3, ["dcluochong", "old_dcaichen"], ["character:dc_tengfanglan", "die:dc_tengfanglan"]],

    //海外
    old_tw_huojun: ["male", "shu", 4, ["twsidai", "old_twjieyu"], ["character:tw_huojun", "die:tw_huojun"]],
    old_tw_guohuai: ["male", "wei", 4, ["old_twjingce", "old_yuzhang"], ["character:tw_guohuai", "die:tw_guohuai"]],
    oldx_quancong: ["male", "wu", 4, ["old_zhenshan"], ["character:quancong", "die:quancong"]],
    old_tw_baoxin: ["male", "qun", 4, ["old_twmutao", "old_twyimou"], ["character:tw_baoxin", "die:tw_baoxin"]],
    old_tw_zhangmancheng: ["male", "qun", 4, ["twfengji", "twyiju", "old_twbudao"], ["character:tw_zhangmancheng", "die:tw_zhangmancheng"]],
    old_tw_guanqiujian: ["male", "wei", 4, ["twzhengrong", "twhongju"], ["character:tw_guanqiujian", "die:tw_guanqiujian", "name:毌丘|俭"]],
    old_tw_niufudongxie: ["double", "qun", 4, ["old_twjuntun", "old_twxiongxi", "twxiafeng"], ["character:tw_niufudongxie", "die:tw_niufudongxie", "name:牛|辅-董|翓"]],
    old_xia_tongyuan: ["male", "qun", 4, ["twchaofeng", "old_twchuanshu"], ["character:xia_tongyuan", "die:xia_tongyuan"]],
    old_xia_guanyu: ["male", "qun", 4, ["old_twzhongyi", "old_twchue"], ["character:xia_guanyu", "die:xia_guanyu"]],
    old_huan_zhugeliang: ["male", "shu", "3/4", ["twbeiding", "twjielv", "old_twhunyou"], ["character:huan_zhugeliang", "die:huan_zhugeliang", "name:诸葛|亮"]],
    old_huan_weiyan: ["male", "shu", 4, ["twqiji", "old_twpiankuang"], ["character:huan_weiyan", "die:huan_weiyan"]],
    old_huan_zhugeguo: ["female", "shu", 3, ["old_rexianyuan", "twlingyin"], ["character:huan_zhugeguo", "die:huan_zhugeguo"]],
    old_tw_shen_lvmeng: ["male", "shen", 3, ["old_twgongxin", "old_twshelie"], ["character:tw_shen_lvmeng", "die:tw_shen_lvmeng", "wu"]],
    old_huan_caoang: ["male", "wei", "3/4", ["old_twchihui", "old_twfuxi"], ["character:huan_caoang", "die:huan_caoang"]],
    //其他
    // old_gaowang: ["male", "qun", 3, ["scsanruo"], ["character:scs_gaowang", "die:scs_gaowang", "sex:male_castrated"]],
    diy_zhujun: ["male", "qun", 4, ["xinyangjie", "diy_juxiang", "houfeng"], ["character:sp_zhujun"]],
    diy_liaohua: ["male", "shu", 4, ["redangxian", "diy_fuli"], ["character:xin_liaohua"]],
    diy_zhangfei: ["male", "shu", 4, ["diy_paoxiao", "diy_tishen"], ["character:re_zhangfei"]],
    //改
    wangtaowangyue: ["female", "shu", 3, ["huguan", "yaopei", "mingluan"], ["die:ext:星之梦/audio/die:2"]],
    lm_old_caocao: ["male", "shen", 3, ["lmjunkguixin", "feiying"], ["character:old_caocao", "die:old_caocao"]],
    // lm_sb_menghuo: ["male", "shu", 4, ["sbhuoshou", "lmsbzaiqi", "twqiushou"], ["character:sb_menghuo", "die:sb_menghuo", "zhu", "doublegroup:shu:qun"]],
    // lm_sb_xiahoudun: ["male", "wei", 4, ["lmsbganglie", "sbqingjian"], ["character:sb_xiahoudun", "die:sb_xiahoudun", "name:夏侯|惇"]],
    // lm_sb_jiangwei: ["male", "shu", 4, ["sbtiaoxin", "lmsbzhiji"], ["character:sb_jiangwei", "die:sb_jiangwei"]],
    // lm_re_fazheng: ["male", "shu", 3, ["twenyuan", "rexuanhuo"], ["character:re_fazheng", "die:re_fazheng"]],
    // lm_re_caopi: ["male", "wei", 3, ["rexingshang", "lmfangzhu", "songwei"], ["character:re_caopi", "die:re_caopi", "zhu"]],
    // lm_re_zhangjiao: ["male", "qun", 3, ["xinleiji", "xinguidao", "minihuangtian"], ["character:re_zhangjiao", "die:re_zhangjiao", "zhu"]],
    // lm_re_sunxiu: ["male", "wu", 3, ["miniyanzhu", "minixingxue", "xinzhaofu"], ["character:re_sunxiu", "die:re_sunxiu", "zhu"]],
    // lm_re_liuchen: ["male", "shu", 4, ["minizhanjue", "miniqinwang"], ["character:re_liuchen", "die:re_liuchen", "zhu"]],
    // lm_sunliang: ["male", "wu", 3, ["minikuizhu", "minichezheng", "nzry_lijun"], ["character:sunliang", "die:sunliang", "zhu"]],
    // lm_zhangxiu: ["male", "qun", 4, ["drlt_xiongluan", "drlt_congjian", "nsfuge", "twjuxiang"], ["character:zhangxiu", "die:zhangxiu", "zhu"]],
    // lm_yl_yuanshu: ["male", "qun", 4, ["lmyongsi", "drlt_weidi"], ["character:yl_yuanshu", "die:yl_yuanshu", "zhu"]],
    // lm_liuyu: ["male", "qun", 2, ["xinzhige", "lmzongzuo", "twchongwang"], ["character:liuyu", "die:liuyu", "zhu"]],
    // lm_liuyao: ["male", "qun", 4, ["lmkannan", "twniju"], ["character:liuyao", "die:liuyao", "zhu"]],
    // lm_zhanglu: ["male", "qun", 3, ["miniyishe", "minibushi", "minimidao", "twshijun"], ["character:zhanglu", "die:zhanglu", "zhu"]],
    // lm_liuxie: ["male", "qun", 3, ["minitianming", "minimizhao", "twzhuiting"], ["character:liuxie", "die:liuxie", "zhu"]],
    // lm_tw_mateng: ["male", "qun", 4, ["mashu", "twxiongzheng", "xiongyi", "twluannian"], ["character:tw_mateng", "die:tw_mateng", "zhu"]],
    // lm_jsrg_hansui: ["male", "qun", 4, ["jsrgniluan", "jsrghuchou", "olxiaoxi", "jsrgjiemeng"], ["character:jsrg_hansui", "die:jsrg_hansui", "zhu"]],
    // lm_lvbu: ["male", "qun", 4, ["gz_wushuang", "new_liyu", "yjqingjiao"], ["character:re_lvbu", "die:re_lvbu", "zhu"]],

    //神武
    sw_guanyu: ["male", "shen", 5, ["wushen", "new_wuhun", "shenwuzaishi"], ["character:shen_guanyu", "die:shen_guanyu", "shu"]],
    sw_lvmeng: ["male", "shen", 3, ["shelie", "gongxin", "shenwuzaishi"], ["character:shen_lvmeng", "die:shen_lvmeng", "wu"]],
    sw_zhugeliang: ["male", "shen", 3, ["qixing", "kuangfeng", "dawu", "shenwuzaishi"], ["character:shen_zhugeliang", "die:shen_zhugeliang", "shu", "name:诸葛|亮"]],
    sw_zhouyu: ["male", "shen", 4, ["yeyan", "miniqinyin", "shenwuzaishi"], ["character:shen_zhouyu", "die:shen_zhouyu", "wu"]],
    sw_simayi: ["male", "shen", 4, ["renjie", "sbaiyin", "lianpo", "shenwuzaishi"], ["character:shen_simayi", "die:shen_simayi", "wei", "name:司马|懿"]],
    sw_zhaoyun: ["male", "shen", 2, ["xinjuejing", "relonghun", "shenwuzaishi"], ["character:shen_zhaoyun", "die:shen_zhaoyun", "shu"]],
    sw_caocao: ["male", "shen", 3, ["guixin", "feiying", "shenwuzaishi"], ["character:shen_caocao", "die:shen_caocao", "wei"]],
    sw_lvbu: ["male", "shen", 5, ["baonu", "wumou", "ol_wuqian", "ol_shenfen", "shenwuzaishi"], ["character:shen_lvbu", "die:shen_lvbu", "qun"]],
    sw_liubei: ["male", "shen", 6, ["nzry_longnu", "nzry_jieying", "shenwuzaishi"], ["character:shen_liubei", "die:shen_liubei", "shu"]],
    sw_luxun: ["male", "shen", 4, ["nzry_junlve", "nzry_cuike", "nzry_dinghuo", "shenwuzaishi"], ["character:shen_luxun", "die:shen_luxun", "wu"]],
    sw_zhangliao: ["male", "shen", 4, ["drlt_duorui", "lmzhiti", "shenwuzaishi"], ["character:shen_zhangliao", "die:shen_zhangliao", "wei"]],
    sw_ganning: ["male", "shen", "3/6", ["drlt_poxi", "drlt_jieying", "shenwuzaishi"], ["character:shen_ganning", "die:shen_ganning", "wu"]],
    sw_caopi: ["male", "shen", 5, ["chuyuan", "dengji", "shenwuzaishi"], ["character:shen_caopi", "die:shen_caopi", "wei"]],
    sw_zhenji: ["female", "shen", 4, ["shenfu", "qixian", "shenwuzaishi"], ["character:shen_zhenji", "die:shen_zhenji", "wei"]],
    sw_zhangjiao: ["male", "shen", 3, ["yizhao", "sijun", "tianjie", "shenwuzaishi"], ["character:shen_zhangjiao", "die:shen_zhangjiao", "qun"]],
    sw_diaochan: ["female", "shen", 3, ["minimeihun", "minihuoxin", "shenwuzaishi"], ["character:shen_diaochan", "die:shen_diaochan", "qun"]],

    sw_tw_guanyu: ["male", "shen", 4, ["twwushen", "twwuhun", "shenwuzaishi"], ["character:tw_shen_guanyu", "die:tw_shen_guanyu", "shu"]],
    sw_tw_lvmeng: ["male", "shen", 3, ["old_twshelie", "old_twgongxin", "shenwuzaishi"], ["character:tw_shen_lvmeng", "die:tw_shen_lvmeng", "wu"]],
    sw_wechat_zhugeliang: ["male", "shen", 3, ["wechatqixing", "wechatjifeng", "wechattianfa", "shenwuzaishi"], ["die:shen_zhugeliang", "shu", "name:诸葛|亮"]],

    lm_xurong: ["male", "qun", 4, ["old_xionghuo", "old_shajue", "xr_huyi"], ["character:xurong", "die:xurong"]],

    //其他
    unlock_dongzhao: ["male", "wei", 3, ["olxianlve", "olzaowang"], ["character:ol_dongzhao", "die:ol_dongzhao"]],
    unlock_tianchuan: ["female", "qun", 3, ["pshuying", "psqianjing", "psbianchi"], ["character:yj_tianchuan"]],
    lm_jikang: ["male", "wei", 3, ["qingxian", "fh_juexiang"], ["character:jikang", "die:jikang"]],

    //十常侍
    lm_shichangshi: ["male", "qun", 1, ["scstaoluan", "scschiyan", "scszimou", "scspicai", "scsyaozhuo", "scsxiaolu", "scskuiji", "scschihe", "scsniqu", "scsanruo"], ["character:shichangshi", "die:shichangshi", "sex:male_castrated", "name:张|让-赵|忠-孙|璋-毕|岚-夏|恽-韩|悝-栗|嵩-段|珪-郭|胜-高|望"]],
    lm_zhangrang: ["male", "qun", 4, ["scstaoluan"], ["character:scs_zhangrang", "die:scs_zhangrang", "sex:male_castrated"]],
    lm_zhaozhong: ["male", "qun", 4, ["scschiyan"], ["character:scs_zhaozhong", "die:scs_zhaozhong", "sex:male_castrated"]],
    lm_sunzhang: ["male", "qun", 4, ["scszimou"], ["character:scs_sunzhang", "die:scs_sunzhang", "sex:male_castrated"]],
    lm_bilan: ["male", "qun", 4, ["scspicai"], ["character:scs_bilan", "die:scs_bilan", "sex:male_castrated"]],
    lm_xiayun: ["male", "qun", 4, ["scsyaozhuo"], ["character:scs_xiayun", "die:scs_xiayun", "sex:male_castrated"]],
    lm_hankui: ["male", "qun", 4, ["scsxiaolu"], ["character:scs_hankui", "die:scs_hankui", "sex:male_castrated"]],
    lm_lisong: ["male", "qun", 4, ["scskuiji"], ["character:scs_lisong", "die:scs_lisong", "sex:male_castrated"]],
    lm_duangui: ["male", "qun", 4, ["scschihe"], ["character:scs_duangui", "die:scs_duangui", "sex:male_castrated"]],
    lm_guosheng: ["male", "qun", 4, ["scsniqu"], ["character:scs_guosheng", "die:scs_guosheng", "sex:male_castrated"]],
    lm_gaowang: ["male", "qun", 4, ["scsanruo"], ["character:scs_gaowang", "die:scs_gaowang", "sex:male_castrated"]],
    //头像
    aaAronaPurana: ["", "shen", 9, [], ["unseen"]],
    aaAqua: ["", "shen", 9, [], ["unseen"]],
    abAqua: ["", "shen", 9, [], ["unseen"]],
    aamomo: ["", "shen", 9, [], ["unseen"]],
    aamidori: ["", "shen", 9, [], ["unseen"]],
    aaNina: ["", "shen", 9, [], ["unseen"]],
    aahikari: ["", "shen", 9, [], ["unseen"]],
    aanozomi: ["", "shen", 9, [], ["unseen"]],
    aaKotone: ["", "shen", 9, [], ["unseen"]],

};
export const characterData = lmCharacter;