import { lib, game, ui, get, ai, _status } from "../../../noname.js";
const characterReplaces = {
	//大致按照OL，新杀，手杀，外服，线下，DIY，怀旧的顺序排列。（同服按标，界，谋，sp）
	sunquan: ["old_dm_sunquan", "old_mb_sunquan", "old_sb_sunquan", "old_v_sunquan"],
	zhangrang: ["old_ol_sb_zhangrang", "lm_zhangrang"],
	yl_luzhi: ["old_ol_sb_yl_luzhi"],
	dengai: ["old_ol_sb_dengai", "oldx_ol_sb_dengai", "old_dc_sb_dengai", "old_pot_dengai"],
	dongzhuo: ["old_ol_sb_dongzhuo"],
	madai: ["old_ol_madai"],
	liubiao: ["old_ol_liubiao"],
	wangyi: ["old_ol_wangyi"],
	chengpu: ["old_ol_chengpu"],
	yufan: ["old_ol_yufan"],
	xunyu: ["old_clan_xunyu", "old_dc_sb_xunyu", "dc_sb_xunyu", "star_xunyu", "re_xunyu", "sb_xunyu", "sxrm_xunyu", "xy_xunyu", "clan_xunyu"],
	zhonghui: ["old_clan_zhonghui", "old_xin_zhonghui"],
	yangxiu: ["old_clan_yangxiu"],
	zhangqiying: ["old_zhangqiying"],
	yangfeng: ["old_ol_yangfeng"],
	xuelingyun: ["old_ol_xuelingyun"],
	nanhualaoxian: ["old_ol_nanhualaoxian"],
	qianzhao: ["old_ol_qianzhao"],
	ruiji: ["old_ruiji"],
	zhugejin: ["old_zhugejin"],
	sunce: ["old_sp_sunce", "old_sb_sunce", "old_v_sunce"],
	ol_pengyang: ["old_ol_pengyang"],
	feiyi: ["old_ol_feiyi"],
	hujinding: ["old_ol_hujinding"],
	luyusheng: ["old_ol_luyusheng"],
	tengfanglan: ["old_tengfanglan", "old_dc_tengfanglan"],
	xushu: ["old_dc_xushu", "old_friend_xushu"],
	caorui: ["old_re_caorui"],
	zhangchunhua: ["old_re_zhangchunhua"],
	chengui: ["old_chengui", "old_mb_chengui"],
	tw_zhugejun: ["old_dc_zhugejun"],
	xiahouxuan: ["old_dc_xiahouxuan"],
	zhurong: ["old_dc_sp_zhurong", "old_sb_zhurong"],
	miheng: ["old_yue_miheng"],
	dc_liuli: ["old_dc_liuli"],
	yuechen: ["old_yuechen"],
	dingfeng: ["old_star_dingfeng"],
	fazheng: ["old_star_fazheng", "old_sb_fazheng"],
	liufuren: ["old_liufuren"],
	yuanji: ["old_yuanji"],
	machao: ["old_v_machao"],
	zhangxingcai: ["old_v_zhangxingcai"],
	luxun: ["old_dc_sb_luxun"],
	dc_sb_hulie: ["old_dc_sb_hulie"],
	xuyou: ["old_dc_sb_xuyou"],
	zhuran: ["old_dc_sb_zhuran"],
	zhugeliang: ["old_wu_zhugeliang", "old_huan_zhugeliang"],
	sp_zhugeliang: ["old_sb_sp_zhugeliang", "oldx_sb_sp_zhugeliang"],
	guanyu: ["old_wu_guanyu", "old_sb_guanyu", "old_xia_guanyu"],
	huangfusong: ["old_wu_huangfusong", "old_tw_huangfusong", "old_jsrg_huangfusong"],
	lukang: ["old_wu_lukang"],
	zhujun: ["old_sp_zhujun", "diy_zhujun"],
	lvfan: ["old_sp_lvfan"],
	qiaogong: ["old_qiaogong"],
	xinpi: ["old_sp_xinpi"],
	wujing: ["old_wujing"],
	wangshuang: ["old_sp_wangshuang"],
	wangling: ["old_wangling"],
	liuhui: ["old_mb_liuhui"],
	caomao: ["old_mb_caomao"],
	cuilingyi: ["old_mb_cuilingyi"],
	ol_mengda: ["old_mb_mengda"],
	caocao: ["old_mb_caocao"],
	wuke: ["old_wuke"],
	zhangliao: ["old_hefei_zhangliao", "old_sb_zhangliao"],
	jianggan: ["old_sp_jianggan"],
	guanqiujian: ["old_mb_sp_guanqiujian", "old_tw_guanqiujian"],
	shenpei: ["old_shenpei"],
	liwei: ["old_liwei"],
	yangfu: ["old_yangfu"],
	guozhao: ["old_mb_guozhao"],
	zhenji: ["old_mb_sp_zhenji"],
	zhuzhi: ["old_mb_zhuzhi"],

	//本体没有替换的
	clan_xuncai: ["old_clan_xuncai"],
	clan_xunshi: ["old_clan_xunshi"],
	clan_xunshuang: ["old_clan_xunshuang"],
	clan_hanrong: ["old_clan_hanrong"],
	clan_hanshao: ["old_clan_hanshao"],
	clan_wangmingshan: ["old_clan_wangmingshan"],
	kongshu: ["old_kongshu"],
	wangyan: ["old_wangyan"],
	dengzhong: ["old_dengzhong"],
	zhanghua: ["old_zhanghua"],
	dc_weifeng: ["old_dc_weifeng"],
	hansong: ["old_hansong"],
	renwan: ["old_renwan"],
	liujinliupei: ["old_liujinliupei"],
	pangfengyi: ["old_pangfengyi"],
	zhugejing: ["old_zhugejing"],
	bailingyun: ["old_bailingyun"],
	ruanyu: ["old_ruanyu"],
	xurong: ["old_xurong", "lm_xurong"],
	xin_zhangzhongjing: ["old_xin_zhangzhongjing"],
	zhangbu: ["old_zhangbu"],
	mb_wangjing: ["old_mb_wangjing"],
	fuqian: ["old_fuqian"],

	//神将-按魏蜀吴群排列
	shen_caopi: ["old_shen_caopi", "sw_caopi"],

	shen_jiangwei: ["old_mb_shen_jiangwei", "oldx_mb_shen_jiangwei"],

	shen_sunquan: ["old_dc_shen_sunquan"],

	shen_huatuo: ["old_dc_shen_huatuo"],

	shen_huatuo: ["dc_shen_huatuo", "shen_huatuo", "old_dc_shen_huatuo"],
	shen_jiangwei: ["old_mb_shen_jiangwei", "oldx_mb_shen_jiangwei", "shen_jiangwei"],
	shen_guanyu: ["sw_guanyu", "sw_tw_guanyu"],
	shen_lvmeng: ["old_tw_shen_lvmeng", "sw_lvmeng", "sw_tw_lvmeng", "shen_lvmeng", "tw_shen_lvmeng"],
	shen_zhugeliang: ["sw_zhugeliang", "sw_wechat_zhugelian"],
	shen_zhouyu: ["shen_zhouyu", "sw_zhouyu"],
	shen_simayi: ["shen_simayi", "xin_simayi", "new_simayi", "old_new_simayi", "sw_simayi"],
	shen_zhaoyun: ["sw_zhaoyun"],
	shen_caocao: ["sw_caocao", "lm_old_caocao"],
	shen_lvbu: ["shen_lvbu", "sw_lvbu"],
	shen_liubei: ["sw_liubei"],
	shen_luxun: ["shen_luxun", "sw_luxun"],
	shen_zhangliao: ["sw_zhangliao"],
	shen_ganning: ["shen_ganning", "sw_ganning"],

	shen_zhenji: ["shen_zhenji", "sw_zhenji"],
	shen_zhangjiao: ["sw_zhangjiao"],
	shen_diaochan: ["shen_diaochan", "sw_diaochan"],
};
export default characterReplaces;
