import { lib, game, ui, get, ai, _status } from "../../../noname.js";
const characterReplaces = {
	//大致按照OL，新杀，手杀，外服，线下，DIY，怀旧的顺序排列。（同服按标，界，谋，sp）
	sunquan: ["old_dm_sunquan", "old_mb_sunquan", "old_sb_sunquan", "old_v_sunquan"],
	yl_luzhi: ["old_ol_sb_yl_luzhi"],
	dengai: ["old_ol_sb_dengai", "oldx_ol_sb_dengai", "old_dc_sb_dengai", "old_pot_dengai"],
	dongzhuo: ["old_ol_sb_dongzhuo"],
	madai: ["old_ol_madai"],
	liubiao: ["old_ol_liubiao"],
	wangyi: ["old_ol_wangyi"],
	chengpu: ["old_ol_chengpu"],
	yufan: ["old_ol_yufan"],
	xunyu: ["old_clan_xunyu", "old_dc_sb_xunyu", "dc_sb_xunyu", "star_xunyu", "re_xunyu", "sb_xunyu", "sxrm_xunyu", "xy_xunyu", "clan_xunyu"],
	zhonghui: ["old_clan_zhonghui", "old_xin_zhonghui"],
	yangxiu: ["old_clan_yangxiu"],
	zhangqiying: ["old_zhangqiying"],
	yangfeng: ["old_ol_yangfeng"],
	xuelingyun: ["old_ol_xuelingyun"],
	nanhualaoxian: ["old_ol_nanhualaoxian"],
	qianzhao: ["old_ol_qianzhao"],
	ruiji: ["old_ruiji"],
	zhugejin: ["old_zhugejin"],
	sunce: ["old_sp_sunce", "old_sb_sunce", "old_v_sunce"],
	ol_pengyang: ["old_ol_pengyang"],
	feiyi: ["old_ol_feiyi"],
	hujinding: ["old_ol_hujinding"],
	luyusheng: ["old_ol_luyusheng"],
	tengfanglan: ["old_tengfanglan", "old_dc_tengfanglan"],
	xushu: ["old_dc_xushu", "old_friend_xushu"],
	caorui: ["old_re_caorui"],
	zhangchunhua: ["old_re_zhangchunhua"],
	chengui: ["old_chengui", "old_mb_chengui"],
	tw_zhugejun: ["old_dc_zhugejun"],
	xiahouxuan: ["old_dc_xiahouxuan"],
	zhurong: ["old_dc_sp_zhurong", "old_sb_zhurong"],
	miheng: ["old_yue_miheng"],
	dc_liuli: ["old_dc_liuli"],
	yuechen: ["old_yuechen"],
	dingfeng: ["old_star_dingfeng"],
	fazheng: ["old_star_fazheng", "old_sb_fazheng"],
	liufuren: ["old_liufuren"],
	yuanji: ["old_yuanji"],
	machao: ["old_v_machao"],
	zhangxingcai: ["old_v_zhangxingcai"],
	luxun: ["old_dc_sb_luxun"],
	dc_sb_hulie: ["old_dc_sb_hulie"],
	xuyou: ["old_dc_sb_xuyou"],
	zhuran: ["old_dc_sb_zhuran"],
	zhugeliang: ["old_wu_zhugeliang", "old_huan_zhugeliang"],
	sp_zhugeliang: ["old_sb_sp_zhugeliang", "oldx_sb_sp_zhugeliang"],
	guanyu: ["old_wu_guanyu", "old_sb_guanyu", "old_xia_guanyu"],
	huangfusong: ["old_wu_huangfusong", "old_tw_huangfusong", "old_jsrg_huangfusong"],
	lukang: ["old_wu_lukang"],
	zhujun: ["old_sp_zhujun", "diy_zhujun"],
	lvfan: ["old_sp_lvfan"],
	qiaogong: ["old_qiaogong"],
	xinpi: ["old_sp_xinpi"],
	wujing: ["old_wujing"],
	wangshuang: ["old_sp_wangshuang"],
	wangling: ["old_wangling"],
	liuhui: ["old_mb_liuhui"],
	caomao: ["old_mb_caomao"],
	cuilingyi: ["old_mb_cuilingyi"],
	ol_mengda: ["old_mb_mengda"],
	caocao: ["old_mb_caocao"],
	wuke: ["old_wuke"],
	zhangliao: ["old_hefei_zhangliao", "old_sb_zhangliao"],
	jianggan: ["old_sp_jianggan"],
	guanqiujian: ["old_mb_sp_guanqiujian", "old_tw_guanqiujian"],
	shenpei: ["old_shenpei"],
	liwei: ["old_liwei"],
	yangfu: ["old_yangfu"],
	guozhao: ["old_mb_guozhao"],
	zhenji: ["old_mb_sp_zhenji"],
	zhuzhi: ["old_mb_zhuzhi"],
	caopi: ["old_sb_caopi"],
	jiangwei: ["old_sb_jiangwei"],
	xuhuang: ["old_sb_xuhuang"],
	re_yuanshao: ["old_sb_yuanshao"],
	handang: ["old_sb_handang"],
	huaxiong: ["old_sb_huaxiong"],
	jiaxu: ["old_sb_jiaxu"],
	zhanghe: ["old_sb_zhanghe"],
	guojia: ["old_sb_guojia"],
	gaoshun: ["old_sb_gaoshun"],
	xiahouyuan: ["old_sb_xiahouyuan"],
	lvbu: ["old_sb_lvbu"],
	daqiao: ["old_sb_daqiao"],
	menghuo: ["old_sb_menghuo"],
	zhaoyun: ["old_sb_zhaoyun"],
	huangzhong: ["old_sb_huangzhong"],
	gongsunzan: ["old_sb_gongsunzan"],
	huanggai: ["old_sb_huanggai"],
	ganning: ["old_sb_ganning"],
	xiaoqiao: ["old_sb_xiaoqiao"],
	re_lusu: ["old_pot_lusu"],
	zhangyan: ["old_mb_zhangyan"],
	xinxianying: ["old_pot_xinxianying"],
	dc_chenzhi: ["old_mb_chenzhi"],
	weiyan: ["old_pot_weiyan", "old_huan_weiyan"],
	taishici: ["old_pot_taishici"],
	pot_lougui: ["old_pot_lougui"],
	chendao: ["old_pot_chendao"],
	yuji: ["old_pot_yuji"],
	huojun: ["old_tw_huojun"],
	guohuai: ["old_tw_guohuai"],
	quancong: ["old_quancong"],
	baoxin: ["old_tw_baoxin"],
	dc_zhangmancheng: ["old_tw_zhangmancheng"],
	zhugeguo: ["old_huan_zhugeguo"],
	caoang: ["old_huan_caoang"],
	gexuan: ["old_tw_gexuan"],
	tw_zhangzhao: ["old_tw_zhangzhao"],
	jiangji: ["old_tw_jiangji"],
	caochong: ["old_strong_caochong"],
	yuanshu: ["old_jm_yuanshu"],
	zhoubuyi: ["old_yj_zhoubuyi"],
	wufu: ["old_wufu"],
	lukai: ["old_lukai"],
	majun: ["old_yj_majun"],
	liaohua: ["diy_liaohua"],
	zhangfei: ["diy_zhangfei"],

	//本体没有替换的
	clan_xuncai: ["old_clan_xuncai"],
	clan_xunshi: ["old_clan_xunshi"],
	clan_xunshuang: ["old_clan_xunshuang"],
	clan_hanrong: ["old_clan_hanrong"],
	clan_hanshao: ["old_clan_hanshao"],
	clan_wangmingshan: ["old_clan_wangmingshan"],
	kongshu: ["old_kongshu"],
	wangyan: ["old_wangyan"],
	dengzhong: ["old_dengzhong"],
	zhanghua: ["old_zhanghua"],
	dc_weifeng: ["old_dc_weifeng"],
	hansong: ["old_hansong"],
	renwan: ["old_renwan"],
	liujinliupei: ["old_liujinliupei"],
	pangfengyi: ["old_pangfengyi"],
	zhugejing: ["old_zhugejing"],
	bailingyun: ["old_bailingyun"],
	ruanyu: ["old_ruanyu"],
	xurong: ["old_xurong", "lm_xurong"],
	xin_zhangzhongjing: ["old_xin_zhangzhongjing"],
	zhangbu: ["old_zhangbu"],
	mb_wangjing: ["old_mb_wangjing"],
	fuqian: ["old_fuqian"],
	pangxi: ["old_pangxi"],
	guoyuan: ["old_guoyuan"],
	tw_niufudongxie: ["old_tw_niufudongxie"],
	xia_zhaoe: ["old_xia_zhaoe"],
	yinfuren: ["old_yinfuren"],
	tw_zhanghong: ["old_tw_zhanghong"],
	xunyuxunyou: ["old_xunyuxunyou"],

	//十常侍
	lm_shichangshi: ["lm_shichangshi"],
	zhangrang: ["old_ol_sb_zhangrang", "lm_zhangrang"],
	ol_zhaozhong: ["lm_zhaozhong"],
	lm_sunzhang: ["lm_sunzhang"],
	lm_bilan: ["lm_bilan"],
	lm_xiayun: ["lm_xiayun"],
	lm_hankui: ["lm_hankui"],
	lm_lisong: ["lm_lisong"],
	lm_duangui: ["lm_duangui"],
	lm_guosheng: ["lm_guosheng"],
	lm_gaowang: ["lm_gaowang"],

	//神将-按魏蜀吴群排列
	shen_caopi: ["old_shen_caopi", "sw_caopi"],
	shen_simayi: ["old_new_simayi", "sw_simayi"],
	shen_caocao: ["sw_caocao", "lm_old_caocao"],
	shen_zhangliao: ["sw_zhangliao"],
	shen_zhenji: ["sw_zhenji"],

	shen_jiangwei: ["old_mb_shen_jiangwei", "oldx_mb_shen_jiangwei"],
	shen_guanyu: ["sw_guanyu", "sw_tw_guanyu"],
	shen_zhugeliang: ["sw_zhugeliang", "sw_wechat_zhugelian"],
	shen_zhaoyun: ["sw_zhaoyun"],
	shen_liubei: ["sw_liubei"],

	shen_sunquan: ["old_dc_shen_sunquan"],
	shen_lvmeng: ["old_tw_shen_lvmeng", "sw_lvmeng", "sw_tw_lvmeng"],
	shen_zhouyu: ["sw_zhouyu"],
	shen_luxun: ["sw_luxun"],
	shen_ganning: ["sw_ganning"],

	shen_huatuo: ["old_dc_shen_huatuo"],
	shen_lvbu: ["sw_lvbu"],
	shen_zhangjiao: ["sw_zhangjiao"],
	shen_diaochan: ["sw_diaochan"],
};
export default characterReplaces;
